/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/gold.glb -o src/components/CoinModel/CoinModel.jsx -r public
Author: alex.yefremov (https://sketchfab.com/alex.yefremov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gold-coin-0eb499393b8e46578dde94a0826d131b
Title: gold coin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CoinModel(props) {
  const { nodes, materials } = useGLTF('/models/gold.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.1}>
        <mesh geometry={nodes.pCylinder7_standardSurface1_0.geometry} material={materials.standardSurface1} scale={[9.86, 1.458, 9.86]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/gold.glb')
